sudo: required
services:
- docker
language: java
dist: bionic
jdk:
- openjdk14
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - DOCKER_IMAGE=comment-service-api:1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER
  - secure: kLKDkjoCsn6Wgd6y9uWNJ7HsQeixF4eBQcOPxvgD5anAS4UsQJcNbebvN0agJYtdC5XHzQkF4HiddYW4vjFg9BalS07dxUUBp5G2QixaBz+4uXE5ts/4eGGpYdgpGwMbNYfZi4BDWG2oYZQ8DqskLLSX3buoqbzCkLglj4j6aAJvvTjXMYQeFztHmmprqYYE8H2p8IjxY1pbFIoOU+UF0rosutCbktk0tAIEqbs7uYruyJbY6mWeg7OLnfe6Nm4sBCi/rpocaODf7TOXW5YHPiELhY+hbO0Bxvec8EU6u1BzEqt/f8MJrHoEbrgK/R0qtX7yXL55nC7GMzU8pLM8xnpdfNyhLrz7G4z+wH7mrmstwaiZd2nqGL5Iqp3GAcmcA93w6nwFYvJjIgC51krYhtsGuuzmXmTL7Ns1IFNY/5oOTygXzAESAzS79rv4eSi+ZKoMR3DXEZSIQfB4Fi17EBUFDzbqKq4SUSM/UKYollpyqW6UlUcuTI1YhwJOQptqB2VJD63WvV1/CcWFh//9NTrQzosHWUdsAT/7vVKQaspNyzu188L3fUM6c9tbO6HNgyKnxOIlfYElinNuL4nsUbCHpGLiPKfcfTaWWEPTE0WbgeZMSFayrqsM/Jpwi9s6DCQeai6Tl09mNgM7vYsxLT7J/h4W4z+X+RusHwp2NIY=
  - secure: VrU96bhiHK0+ZpuRnwMS2XXKOVbR0BvupLLhBzAMT9O4Tc+pjZC81jgeVoxvHOKEJR/X/Uq+BL9OVz9wvf53jmb34MoKQY/hmu14We22aeyOat8gnykCOvSbhlEjmpYpUlr/UGL22f69hZy0MVxUv6bm2s2F6geDnzwDhStON70rYYOzNK4ypaF1FKeKJ48+0RA2EHHIUzwq9iHc9fklcBWDzi/EaDws4Q2z5cXNyJWwZoo44Nonf21WNFnQtFNlP47LY0GXkyUDonGh0qxs5YQyGC7/B/NvsCzpuIxJaCBMUgdRoww5rB+qeq530qV+++bMnTfkRjrIuWtt5C0PjgbC5BURYJQDggCx89Y4QmQY91LAyUyJChXeZ6H3ubrstkFRHMlLhfZUkrGZ7pDfJGFmvZlHABD4rUxkYfIL/5Cw6rodTP+PikJ4mqnEZ6ATvREojoIZkfV3M4kROe6ETvIFo8qSBjbWpM3uB0Ct4rFU4UkSpz4/OoCjwf02Vq1mlVbbQ/lKijGqwJeSvBeUm/vE0x+g2IaU8AEq297l5D6NLERnLWXjE7wK4R8tEgYjCVCxu2LRhYisyr+oIILHxL1eJIG1rTGcnvd7Qdth7DiZd2Z8T2/7laXLvM9Z8M3dnz+Ot+ip4aZiuE2U7J+UvLlPtG0ko6QbwOExEWjsJZI=
script:
- mvn clean package -U
- docker build -t "$DOCKER_USERNAME"/"$DOCKER_IMAGE" -t "$DOCKER_USERNAME"/"comment-service-api:latest"
  .
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push "$DOCKER_USERNAME"/"$DOCKER_IMAGE"
- docker push "$DOCKER_USERNAME"/"comment-service-api:latest"
