kumuluzee:
  name: comment-service-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080

  cors-filter:
    servlet:
      allow-origin: "*"
      allow-subdomains: true
      supported-methods: "GET, POST, DELETE, HEAD, OPTIONS, PUT"

rest-config:
  maintenance-mode: true